### ISSUE TITLE
OR gates do not work

### ISSUE THREAD

**Issue by TheRetroSnake** [BenVlodgi/BEE2.4#340] opened 2016-05-28 17:49 UTC
So, few days ago I installed BEE 2.4, and tried to make maps with OR gates. This worked fine in earlier versions of the BEE mod, but now, neither of the OR gates work at all. AND gates work fine, but when OR gate receives a signal it doesn't do a thing. I tried this a few times and for pre-exiting maps with OR gates as well as new maps, but it does not work at all.

**Comment by TeamSpen210** [comment] 2016-05-29 00:52
I can't replicate this, they appear to work fine. Turn on `developer 2`, then paste the results after activating and deactivating the gate.

**Comment by TheRetroSnake** [comment] 2016-05-29 15:29
http://pastebin.com/LXt6UwFH

I noticed the bug only happens when you use triggers; for example using pressure plates works just fine. However it seems using triggers with AND gates also works as intended. I also noticed the icons for the OR gate being activated or not sometimes was visible and sometimes not, not sure if this is intentional or bug.

**Comment by TheReviewers** [comment] 2016-05-29 20:07
What are pressure plates?

**Comment by TeamSpen210** [comment] 2016-05-29 22:14
Floor buttons probably.

**Comment by TheRetroSnake** [comment] 2016-05-29 22:53
As seen on the screenshots, yes

**Comment by TeamSpen210** [comment] 2016-09-23 06:06
This is fixed - it's a duplicate of #400.

**Closed by TeamSpen210** 2016-09-23 06:06 UTC
Labels: bug
