### ISSUE TITLE
Maps won't compile.

### ISSUE THREAD

**Issue by QuantiX999** [BenVlodgi/BEE2.4#339] opened 2016-05-28 16:53 UTC
If BEE 2.4 installed, maps won't compile. Style and items doesn't matter. Even with original style and items they won't compile. Here is the console message:

> VBSP failed.
> 
> [I] vbsp: BEE2.4.0pr20 VBSP hook initiallised.
> [I] cond.core: Imported all conditions modules!
> [I] vbsp: Map path is "C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
> [I] vbsp: New path: "C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
> [I] vbsp: Clearing inject/ directory..
> [I] vbsp: PeTI map detected!
> [I] vbsp: Loading settings...
> [W] instanceLocs: None in vals: False
> [W] cond.core: Invalid weight! ()
> [W] cond.core: Invalid weight! ()
> [W] cond.core: Invalid weight! ()
> [W] cond.core: Invalid weight! ()
> [W] BEE2_config: Config "C:\Users
>  |_spod\Documents\���������\BEE 2.4\config/compile.cfg" not found! Using defaults...
> 
> [I] vbsp: Settings Loaded!
> [I] vbsp: Parsing Map...
> [I] vbsp: Reading Map...
> [I] vbsp: Loading complete!
> [I] vbsp: Using random SP Exit (2)
> [I] vbsp: Using random SP Entry (7)
> [I] vbsp: Game Mode: SP
> [I] vbsp: Is Preview: True
> [I] cond.core: Checking Conditions...
> [I] cond.catwalks: Starting catwalk generator...
> [I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
> [I] cond.scaffold: Finished Scaffold generation!
> [I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
> [W] cond.core: Debug: checking-door = <Entity>: 
>  | {
>  | 	 file = "instances/BEE2/p1/elevator_sp/door_frame_white.vmf"
>  | 	 origin = "1088 832 64"
>  | 	 targetname = "doorexit2"
>  | 	 classname = "func_instance"
>  | 	 angles = "-90 90 0"
>  | }
>  |_
> 
> [W] cond.core: Debug: norm_with_door
> [I] vbsp: Elevator type: NONE
> [I] voiceLine: Adding Voice Lines!
> [I] voiceLine: Adding Base instance!
> [I] voiceLine: Quote events: []
> [I] voiceLine: Generating responses data..
> [I] voiceLine: Line "??" is disabled..
> [I] voiceLine: Line "??" is disabled..
> [I] voiceLine: Adding quote: "Line"
>  | 	{
>  | 	"ID" "GENERIC_3"
>  | 	"choreo" "scenes/npc/sphere03/bw_sp_a4_intro_moat03.vcd"
>  | 	}
>  |_
> 
> [I] voiceLine: End-commands: 
> [I] voiceLine: 0 Mid quotes
> [I] voiceLine: Done!
> [I] vbsp: Setting Portalgun:
> [I] vbsp: Blue: Y, Orange: Y
> [I] vbsp: Done!
> [I] cond.core: Map has attributes: ['fizzler', 'cube', 'cubedropperstandard', 'cubedropper', 'cubestandard', 'buttonacceptscube', 'weightedbutton', 'floorbutton', 'fr_csf', 'buttonacceptsball', 'pack_p1_radio_clean', 'spawn_dual']
> [I] cond.core: instanceLocs cache: CacheInfo(hits=14007, misses=276, maxsize=256, currsize=256)
> [I] cond.core: Style Vars: {'p1_wportal_strips': False, 'p1_ported_pgun': False, 'multiversecave': False, 'unlockdefault': False, 'bee_show_trigger': False, 'doorcameras': True, 'nomidvoices': False, 'allowgoomist': True, 'fixfizzlerbump': False}
> [I] cond.core: Global instances: {'instances/BEE2/p1/elevator_sp/cache_cam.vmf', 'instances/BEE2/p1/global_ents.vmf', 'instances/BEE2/p1/items/cube/cache_box.vmf'}
> [I] vbsp: Adding Music...
> [I] vbsp: Adding Global PTI Ents
> [I] vbsp: Editing Other Entities...
> [I] vbsp: Changing goo sides...
> [I] vbsp: Done!
> [I] vbsp: Editing Brushes...
> [I] vbsp: Make Bottomless Pit: False
> [I] vbsp: Adding Goo Mist...
> [I] vbsp: Done!
> [I] vbsp: Editing Overlays...
> [I] vbsp: Editing Triggers...
> [I] vbsp: Collapsing goo triggers...
> [I] vbsp: Done!
> [I] vbsp: Editing Brush Entities...
> [I] vbsp: Removing static indicator toggles...
> [I] vbsp: Done!
> [I] vbsp: Editing WorldSpawn
> [I] vbsp: Making Pack list...
> [I] vbsp: "#scripts/bee2_snd/portal_sounds.txt"
> [I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_csf_center.vmt"
> [I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_csf_left.vmt"
> [I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_csf_right.vmt"
> [I] vbsp: "materials/BEE2/fizz/fourthreaper/compressed_smoke_field.vmt"
> [I] vbsp: "materials/BEE2/fizz/fourthreaper/player_clip_electric.vmt"
> [I] vbsp: "materials/BEE2/ind_p1/corner_floor.vmt"
> [I] vbsp: "materials/BEE2/ind_p1/corner_wall.vmt"
> [I] vbsp: "materials/BEE2/ind_p1/p1_antline_floor_double.vtf"
> [I] vbsp: "materials/BEE2/ind_p1/p1_antline_wall_double.vtf"
> [I] vbsp: "materials/BEE2/ind_p1/straight_floor.vmt"
> [I] vbsp: "materials/BEE2/ind_p1/straight_wall.vmt"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/box_paint_blue.vtf"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/box_paint_orange.vtf"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/metal_box.vmt"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/metal_box.vtf"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_bounce.vmt"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp.vmt"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp.vtf"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp_bounce.vmt"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp_speed.vmt"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_exponent.vtf"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_normal.vtf"
> [I] vbsp: "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_speed.vmt"
> [I] vbsp: "materials/BEE2/models/props_p1/cust_fizz.vmt"
> [I] vbsp: "materials/BEE2/models/props_p1/cust_fizz.vtf"
> [I] vbsp: "materials/BEE2/models/props_p1/cust_fizz_light.vmt"
> [I] vbsp: "materials/BEE2/models/props_p1/cust_fizz_light.vtf"
> [I] vbsp: "materials/BEE2/models/props_p1/floor_button/p1_button.vmt"
> [I] vbsp: "materials/BEE2/models/props_p1/floor_button/p1_button.vtf"
> [I] vbsp: "materials/BEE2/models/props_p1/floor_button/p1_button_exponent.vtf"
> [I] vbsp: "materials/BEE2/models/props_p1/floor_button/p1_button_normal.vtf"
> [I] vbsp: "materials/BEE2/models/props_p1/walllight_sheet.vmt"
> [I] vbsp: "materials/BEE2/models/props_p1/walllight_sheet.vtf"
> [I] vbsp: "materials/BEE2/p1/light_recessedcool_glow.vmt"
> [I] vbsp: "materials/BEE2/p1/metalwall048b_lrg.vmt"
> [I] vbsp: "materials/BEE2/p1/metalwall048b_lrg.vtf"
> [I] vbsp: "materials/BEE2/p1/metalwall048b_lrg_dx8.vtf"
> [I] vbsp: "materials/BEE2/p1/metalwall048b_lrg_height-ssbump.vtf"
> [I] vbsp: "materials/BEE2/p1/metalwall048b_lrg_normal.vtf"
> [I] vbsp: "materials/BEE2/p1/metalwall048b_med.vmt"
> [I] vbsp: "materials/BEE2/p1/metalwall048b_med.vtf"
> [I] vbsp: "materials/BEE2/p1/metalwall048b_med_dx8.vtf"
> [I] vbsp: "materials/BEE2/p1/metalwall048b_med_height-ssbump.vtf"
> [I] vbsp: "materials/BEE2/p1/metalwall048b_med_normal.vtf"
> [I] vbsp: "materials/BEE2/p1/modular_wall_light.vmt"
> [I] vbsp: "materials/BEE2/p1/obs/detail_concrete_03.vtf"
> [I] vbsp: "materials/BEE2/p1/obs/metaldoor028a.vmt"
> [I] vbsp: "materials/BEE2/p1/obs/metaldoor028a.vtf"
> [I] vbsp: "materials/BEE2/p1/obs/observation_tilefloor001a.vmt"
> [I] vbsp: "materials/BEE2/p1/obs/observation_tilefloor001a.vtf"
> [I] vbsp: "materials/BEE2/p1/obs/observationwall_001a.vmt"
> [I] vbsp: "materials/BEE2/p1/obs/observationwall_001a.vtf"
> [I] vbsp: "materials/BEE2/p1/obs/observationwall_001a_normal.vtf"
> [I] vbsp: "materials/BEE2/p1/obs/observationwall_001b.vmt"
> [I] vbsp: "materials/BEE2/p1/obs/observationwall_001b.vtf"
> [I] vbsp: "materials/BEE2/p1/obs/observationwall_001b_height-ssbump.vtf"
> [I] vbsp: "materials/BEE2/p1/overlay_light_gradient.vtf"
> [I] vbsp: "models/BEE2/props_ingame/p1_metal_box.dx90.vtx"
> [I] vbsp: "models/BEE2/props_ingame/p1_metal_box.mdl"
> [I] vbsp: "models/BEE2/props_ingame/p1_metal_box.phy"
> [I] vbsp: "models/BEE2/props_ingame/p1_metal_box.vvd"
> [I] vbsp: "models/BEE2/props_ingame/sign_frame_1_wback.dx90.vtx"
> [I] vbsp: "models/BEE2/props_ingame/sign_frame_1_wback.mdl"
> [I] vbsp: "models/BEE2/props_ingame/sign_frame_1_wback.phy"
> [I] vbsp: "models/BEE2/props_ingame/sign_frame_1_wback.vvd"
> [I] vbsp: "models/BEE2/props_p1/cust_fizzler.dx90.vtx"
> [I] vbsp: "models/BEE2/props_p1/cust_fizzler.mdl"
> [I] vbsp: "models/BEE2/props_p1/cust_fizzler.phy"
> [I] vbsp: "models/BEE2/props_p1/cust_fizzler.vvd"
> [I] vbsp: "models/BEE2/props_p1/door_frame_thick.dx90.vtx"
> [I] vbsp: "models/BEE2/props_p1/door_frame_thick.mdl"
> [I] vbsp: "models/BEE2/props_p1/door_frame_thick.phy"
> [I] vbsp: "models/BEE2/props_p1/door_frame_thick.vvd"
> [I] vbsp: "models/BEE2/props_p1/floor_button_base.dx90.vtx"
> [I] vbsp: "models/BEE2/props_p1/floor_button_base.mdl"
> [I] vbsp: "models/BEE2/props_p1/floor_button_base.phy"
> [I] vbsp: "models/BEE2/props_p1/floor_button_base.vvd"
> [I] vbsp: "models/BEE2/props_p1/floor_button_top.dx90.vtx"
> [I] vbsp: "models/BEE2/props_p1/floor_button_top.mdl"
> [I] vbsp: "models/BEE2/props_p1/floor_button_top.phy"
> [I] vbsp: "models/BEE2/props_p1/floor_button_top.vvd"
> [I] vbsp: "models/BEE2/props_p1/obs_light.dx90.vtx"
> [I] vbsp: "models/BEE2/props_p1/obs_light.mdl"
> [I] vbsp: "models/BEE2/props_p1/obs_light.phy"
> [I] vbsp: "models/BEE2/props_p1/obs_light.vvd"
> [I] vbsp: "models/BEE2/props_p1/security_camera.dx80.vtx"
> [I] vbsp: "models/BEE2/props_p1/security_camera.dx90.vtx"
> [I] vbsp: "models/BEE2/props_p1/security_camera.mdl"
> [I] vbsp: "models/BEE2/props_p1/security_camera.phy"
> [I] vbsp: "models/BEE2/props_p1/security_camera.sw.vtx"
> [I] vbsp: "models/BEE2/props_p1/security_camera.vvd"
> [I] vbsp: "scripts/vscripts/BEE2/change_model.nut"
> [I] vbsp: "scripts/vscripts/BEE2/change_models.nut"
> [I] vbsp: "sound/BEE2/p1/doorstop1.wav"
> [I] vbsp: "sound/BEE2/p1/garage_stop1.wav"
> [I] vbsp: "sound/BEE2/p1/wall_move5.wav"
> [I] vbsp: Packlist written!
> [I] vbsp: Generating VRAD config...
> [I] vbsp: Saving New Map...
> [I] vbsp: Complete!
> [I] vbsp: Calling original VBSP...
> [I] vbsp: Arguments: "C:\Program Files\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
> [I] <Valve>: Valve Software - vbsp.exe (Aug 26 2015)
>  | 2 threads
>  | materialPath: C:\Program Files\Steam\steamapps\common\Portal 2\portal2\materials
>  | Loading C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
>  | ConVarRef gpu_level doesn't point to an existing ConVar
>  | fixing up env_cubemap materials on brush sides...
>  | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (1)
>  | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
>  | Processing areas...done (0)
>  | Building Faces...done (0)
>  | Chop Details...done (0)
>  | Find Visible Detail Sides...
>  | Merged 446 detail faces...done (0)
>  | Merging details...done (0)
>  | FixTjuncs...
>  | PruneNodes...
>  | WriteBSP...
>  | done (0)
>  | writing C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.prt...Building visibility clusters...
>  | done (0)
>  | Finding displacement neighbors...
>  | Finding lightmap sample positions...
>  | Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
>  | material "decals/overlay_light_gradient" not found.
>  | Building Physics collision data...
>  | done (1) (582975 bytes)
>  | Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
>  | Compacting texture/material tables...
>  | Reduced 2207 texinfos to 580
>  | Reduced 64 texdatas to 52 (2032 bytes to 1728)
>  | Writing C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp
>  | 
>  | nummapplanes:     (  4566 / 65536 )
>  | nummapbrushes:    (  1613 /  8192 )
>  | nummapbrushsides: ( 12721 / 65536 )
>  | num_map_overlays: (    15 /   512 )
>  | nummodels:        (    77 /  1024 )
>  | num_entities:     (   398 / 16384 )
>  | 
>  | 11 seconds elapsed
>  |_
> 
> [I] vbsp: VBSP Done!
> [I] vbsp: Retrieved counts: {'entity': ('398', '16384'), 'overlay': ('15', '512'), 'brush': ('1613', '8192')}
> [I] BEE2_config: Saving changes in config "C:\Users
>  |_spod\Documents\���������\BEE 2.4\config/compile.cfg"!
> 
> Traceback (most recent call last):
>   File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
>   File "vbsp_launch.py", line 7, in <module>
>   File "F:\Git\BEE2.4\src\vbsp.py", line 3860, in main
>   File "F:\Git\BEE2.4\src\vbsp.py", line 3620, in run_vbsp
>   File "F:\Git\BEE2.4\src\vbsp.py", line 3681, in process_vbsp_log
>   File "F:\Git\BEE2.4\src\BEE2_config.py", line 53, in save
>   File "F:\Git\BEE2.4\src\utils.py", line 903, in __enter__
>   File "F:\Git\BEE2.4\src\utils.py", line 893, in make_tempfile
>   File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
>   File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
>   File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
>   File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
>   File "c:\python\32-bit\3.4\lib\os.py", line 237, in makedirs
> OSError: [WinError 123] �������������� ������ � ����� �����, ����� ����� ��� ����� ����: 'C:\\Users\nspod'

_**What to do?**_

**Comment by TeamSpen210** [comment] 2016-05-29 00:54
This is a duplicate of TeamSpen210/BEE2-items/#591.

**Closed by TeamSpen210** 2016-05-29 00:54 UTC
