### ISSUE TITLE
Mac - maps/instances path not detected

### ISSUE THREAD

**Issue by dunkler-schatten** [BenVlodgi/BEE2.4#282] opened 2016-04-11 19:45 UTC
BEE2.4 not startable.
Error by BEE2 Exec.

Last login: Mon Apr 11 21:25:00 on ttys000
Carstens-Mac-mini:~ xxxxxx
$ /Users/xxxxxxx/Desktop/BEE2.4_pr19_1_mac/bin/BEE2 
dyld: Library not loaded: /Library/Frameworks/Python.framework/Versions/3.4/Python
  Referenced from: /Users/xxxxxxxxxx/Desktop/BEE2.4_pr19_1_mac/bin/BEE2
  Reason: image not found
Trace/BPT trap: 5

Python is installed on my Mac.

BEE2.4 under Windows OK.
Sorry for my bad English.
Dunkler-Schatten

**Comment by dunkler-schatten** [comment] 2016-04-12 05:57
So 1 error found.
If on the Mac a higher Python version is installed as version 3.4.4 can Bee2.4 not be started.
BEE requires apparently under mac exact Python version 3.4.4 to work?
Now it seems to work.

But.......
BEE Exec Open File directly does not work.
Error file is Broken.
BEE can be opened only when you open them directly in the terminal.
Using drag and drop
And......
after exporting a pallet may no more chambers create error of Peti Editor. :-(
"When creating the puzzle was an error
![bildschirmfoto 2016-04-12 um 07 54 56](https://cloud.githubusercontent.com/assets/18405990/14451058/11e6f4b0-0084-11e6-99da-dd1ff15cc2cf.png)
"
Now i can´t create test Chambers anymore.

**Comment by dunkler-schatten** [comment] 2016-04-12 06:23
Here is the error Code from Portal 2 Console:
The same problem in Windows.

VBSP failed.

[I] vbsp: BEE2.4.0pr19 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "/Users/xxxxxxx/Library/Application Support/Steam/steamapps/common/Portal 2/sdk_content/maps/preview.vmf"
[I] vbsp: New path: "/Users/xxxxxxxxx/Library/Application Support/Steam/steamapps/common/Portal 2/sdk_content/maps/styled/preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.catwalks: Starting catwalk generator...
[I] cond.core: Exiting empty condition!
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] vbsp: Elevator type: NONE
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Quote events: []
[I] voiceLine: []
[I] voiceLine: No responses data..
[I] voiceLine: Mid quotes: []
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] cond.core: Map has attributes: 
[I] cond.core: Style Vars:
[I] cond.core: Global instances: 
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: True
[I] vbsp: Creating Bottomless Pits...
[I] vbsp: Done!
[I] vbsp: Clumping: 108 clumps (+ 0 special)
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "materials/BEE2/metalwall_bts_001b.vmt"
[I] vbsp: "materials/BEE2/metalwall_bts_001b_normal.vtf"
[I] vbsp: "materials/BEE2/squarebeams_bts.vmt"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
Calling original VBSP...
"/Users/xxxxxxxxxxxx/Library/Application Support/Steam/steamapps/common/Portal 2/bin/vbsp_osx_original" -game "/Users/xxxxxxxxxxxx/Library/Application Support/Steam/steamapps/common/Portal 2/portal2/" "/Users/xxxxxxxxxxx/Library/Application Support/Steam/steamapps/common/Portal 2/sdk_content/maps/styled/preview.vmf"
Valve Software - vbsp.exe (Aug 26 2015)
8 threads
materialPath: /Users/xxxxxxxxxxx/Library/Application Support/Steam/steamapps/common/Portal 2/portal2/materials
Loading /Users/xxxxxxxxxxx/Library/Application Support/Steam/steamapps/common/Portal 2/sdk_content/maps/styled/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/bee2/bts/elevator_sp/entrance_corridor_1.vmf
VBSP failed! (1)

regards 
Dunkler-Schatten

**Comment by Konclan** [comment] 2016-04-13 22:36
This is caused by a missing instance entrance_corridor_1.vmf

**Comment by TeamSpen210** [comment] 2016-04-14 04:14
That's probably not the issue, it's a bug with how Macs search for instances. I'll fix it in the next release.

**Comment by dunkler-schatten** [comment] 2016-04-14 07:10
@Konclan 
The problem is that the "instance entrance corridor 1.vmf" file exists in my Portal 2 folder he does not find them anyway.
Delete all files and re-download and install via Steam I have tried several times no effect.
Have Windows 8.1 as a trial install because it runs everything now. O.o But unfortunately not the Mac. There's the old problem.
but I also do not understand why it suddenly goes in Windows ???
Windows is not a alternativ for me. :-/

@TeamSpen210 
Yes, I also think that it could be because.
The file system of Windows and Mac is so very different.
Oh and by the way. I miss a few Cool Items in the MOD 2.4.
many you have in "tspenAddons". These are so far as I have read not compatible BEE2.4
Whatever i love The Mod :-) Respect Team Bee

-----------
Thanks everybody for your helps. I hope you can understand my english :-D

**Comment by TeamSpen210** [comment] 2016-04-14 07:44
In particular, it's a bug in Valve's code where they search for the text `"\\maps\\"` in the file path to locate the instances. On Macs and Linux though they use `/` to separate things, so it always fails. Default PETI happens to work since the `instances` folder is in the same place as the VMF, but ours is saved in a different place.

**Comment by dunkler-schatten** [comment] 2016-05-02 17:01
Yeaaa Mod is running and no errors on Mac. Thank you! :-D

**Comment by Konclan** [comment] 2016-05-02 17:04
@dunkler-schatten close the issue with the "Close Issue" button next to the green "Comment" button

**Closed** 2016-05-02 19:21 UTC
Labels: bug, fixed
