### ISSUE TITLE
"Oh, Fiddlesticks" Music Error

### ISSUE THREAD

**Issue by QuantiX999** [BenVlodgi/BEE2.4#413] opened 2016-10-17 18:38 UTC
Whatever music I choose, it plays normally at the preview, but when uploaded, it says "Oh, fiddlesticks" and silence...

**Comment by Jadeygaming** [comment] 2016-10-17 20:56
TeamSpen Hasn't Been Replying To Issues Latly

**Comment by TeamSpen210** [comment] 2016-10-17 22:31
This has been fixed for the next release.

**Comment by Jadeygaming** [comment] 2016-10-17 23:34
Did He Really Skip My Issue?

**Comment by LautaroL20** [comment] 2016-10-26 19:31
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/679

**Closed** 2016-11-23 07:00 UTC
Labels: bug, compiler, fixed in next pre-release
