### ISSUE TITLE
Original Clean Style Problem

### ISSUE THREAD

**Issue by GLiTcH2** [BenVlodgi/BEE2.4#318] opened 2016-05-07 02:21 UTC
When I enable the Original Clean style and rebuild the chamber the ceiling does not seem to render making a complete white space, However you can place portals on it despite in the editor having all walls set to non-portal surface....
![20160506191331_1](https://cloud.githubusercontent.com/assets/19172857/15089734/aa176a14-13bf-11e6-808a-d7f8a98ef287.jpg)

**Comment by Konclan** [comment] 2016-05-07 02:28
This has been reported already, its apparently a typo in the material or something

**Comment by GLiTcH2** [comment] 2016-05-07 03:53
Oh ok, I tried searching to see if it had been posted before but I guess I missed it!

**Comment by LautaroL20** [comment] 2016-05-07 06:41
This is a duplicate of https://github.com/TeamSpen210/BEE2-items/issues/512

**Closed** 2016-05-07 08:35 UTC
Labels: bug, duplicate
