### ISSUE TITLE
(DEV Version) The beemod "Style Selector Window" and  "Music Chooser Window" wouldn´t change the Style / Music when clicking on the icon if the resolution of the window is small

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#436] opened 2016-12-03 08:56 UTC
Take a look at this GIF and play atention how the "Original Clean" icon is being clicked all the time without any effect, under the export options window:

![GIF](https://cloud.githubusercontent.com/assets/12244376/20858139/9570cb0c-b91c-11e6-9221-56a171d16302.gif)

**Comment by TeamSpen210** [comment] 2016-12-04 00:36
Duplicate of #437.

**Closed** 2016-12-04 00:36 UTC
Labels: duplicate

**Comment by LautaroL20** [comment] 2016-12-04 00:43
Yep. Since it was something of the Dev version, i didn´t know where to post it.
